### ISSUE TITLE
Pipe causes segmentation fault on macOS

### ISSUE THREAD

**Issue by 0ihsan** [chrisalcantara/csv2json#9]
in `zsh`
```sh
❯ cat test-data/data.csv | ./csv2json
zsh: done                cat data.csv |
zsh: segmentation fault  csv2json
```
in `sh`
```sh
sh-3.2$ cat test-data/data.csv | ./csv2json
Segmentation fault: 11
sh-3.2$
```
By the way I don't know if this is related specifically to the macOS. I also updated the code a bit but I don't think they are related to this issue, see: [my changes](https://github.com/ihsanturk/csv2json/commits/master).

I really liked the coding style, thanks.

**Comment by chrisalcantara** [comment]
@0ihsan I like your changes. You're welcome to make a PR, and I'll review.

**Comment by chrisalcantara** [comment]
> By the way I don't know if this is related specifically to the macOS.
I ran through the compilation and build process and did not run into the seg fault in 10.15.7 I did run into some unicode errors on Linux, but that was related to the CSV file piped into the program.

What are your machine's specs?
